name: Scanners (SAST, SCA, SS)

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: "0 8 * * 1"

jobs:
  sast:
    name: SAST
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: fluidattacks/sast-action@1.3.0
        id: scan
        with:
          scan_config_path: .github/sast-config.yaml
          scanner_mode: full

      - name: Fail if vulnerabilities found
        if: steps.scan.outputs.vulnerabilities_found == 'true'
        run: exit 1

      - name: Upload CSV
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sast-results-csv
          path: results.csv

  sca:
    name: SCA
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - uses: fluidattacks/sca-action@1.2.0
        id: scan
        with:
          scan_config_path: .github/sca-config.yaml
          scanner_mode: full

      - name: Fail if vulnerabilities found
        if: steps.scan.outputs.vulnerabilities_found == 'true'
        run: exit 1

      - name: Upload CSV
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sca-results-csv
          path: results.csv

  ss:
    name: Secret Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: fluidattacks/ss-action@0.2.0
        id: scan
        with:
          scan_config_path: .github/ss-config.yaml
          scanner_mode: full

      - name: Fail if vulnerabilities found
        if: steps.scan.outputs.vulnerabilities_found == 'true'
        run: exit 1

      - name: Upload CSV
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ss-results-csv
          path: results.csv
